#!/bin/bash
set -e

# Uruchamiamy polecenia psql z wykorzystaniem zmiennych z pliku .env
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL #POSTGRES_DB = db warehouse
    CREATE USER $POSTGRES_WAREHOUSE_USER WITH PASSWORD '$POSTGRES_WAREHOUSE_PASSWORD';
    ALTER DATABASE $POSTGRES_DB OWNER TO $POSTGRES_WAREHOUSE_USER;

    CREATE DATABASE $POSTGRES_ORDER_NAME;
    CREATE USER $POSTGRES_ORDER_USER WITH PASSWORD '$POSTGRES_ORDER_PASSWORD';
    ALTER DATABASE $POSTGRES_ORDER_NAME OWNER TO $POSTGRES_ORDER_USER;

    CREATE DATABASE $POSTGRES_FORKLIFT_NAME;
    CREATE USER $POSTGRES_FORKLIFT_USER WITH PASSWORD '$POSTGRES_FORKLIFT_PASSWORD';
    ALTER DATABASE $POSTGRES_FORKLIFT_NAME OWNER TO $POSTGRES_FORKLIFT_USER;
EOSQL

