spring.application.name=api-order
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false
server.port=8081

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_ORDER_NAME}
spring.datasource.username=${POSTGRES_ORDER_USER}
spring.datasource.password=${POSTGRES_ORDER_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=health,info,beans
management.info.env.enabled=true