spring.application.name=api-order
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false
server.port=8081

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_ORDER_NAME}
spring.datasource.username=${POSTGRES_ORDER_USER}
spring.datasource.password=${POSTGRES_ORDER_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

management.endpoints.web.exposure.include=health,info,beans
management.info.env.enabled=true