server:
  port: 8080

warehouse:
  api:
    base-url: http://${WAREHOUSE_HOST:localhost}:8082

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "io.swiczka.github.sharedcommon.events,io.swiczka.github.sharedcommon.helpers"
    consumer:
      group-id: gateway-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "io.swiczka.github.sharedcommon.events,io.swiczka.github.sharedcommon.helpers"
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: order
              predicates:
                - Path=/api/order/**,/api/order
              uri: http://${ORDER_HOST:localhost}:8081
            - id: warehouse
              predicates:
                - Path=/api/warehouse/**,/api/warehouse,/api/package/**,/api/package
              uri: http://${WAREHOUSE_HOST:localhost}:8082
            - id: forklift
              predicates:
                - Path=/api/forklift/**,/api/forklift
              uri: http://${FORKLIFT_HOST:localhost}:8083

