server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: RequestSize
              args:
                maxSize: 1MB
            - name: RequestHeaderSize
              args:
                maxSize: 16KB
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10   # ile requestów na sekundę
                redis-rate-limiter.burstCapacity: 20   # maksymalny chwilowy skok
                key-resolver: "#{@userKeyResolver}"    # nazwa beana w Javie

          routes:
            - id: order
              predicates:
                - Path=/api/order/**,/api/order
              uri: http://${ORDER_HOST:localhost}:8081
            - id: warehouse
              predicates:
                - Path=/api/warehouse/**,/api/warehouse
              uri: http://${WAREHOUSE_HOST:localhost}:8082
            - id: forklift
              predicates:
                - Path=/api/forklift/**,/api/forklift
              uri: http://${FORKLIFT_HOST:localhost}:8083