spring.application.name=api-warehouse
server.port=8082

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_WAREHOUSE_NAME}
spring.datasource.username=${POSTGRES_WAREHOUSE_USER}
spring.datasource.password=${POSTGRES_WAREHOUSE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#works similar as postgres (puts variable when in container and puts localhost when run locally)
spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

management.endpoints.web.exposure.include=health,info,beans
management.info.env.enabled=true
